name: Build and Release Flatpak

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build_flatpak:
    name: Build flatpak
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: env
        run: |
          cat build.env >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build flatpak
        run: |
          ./build-scripts/build-flatpak.sh "${{ env.FLUTTER_VERSION }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ./ywallet.flatpak
            ./zwallet.tgz
            ./libwarp_api_ffi.so
