name: Build and Release Windows (No docker)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build_win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: env
        run: |
          type build.env >> $env:GITHUB_ENV

      - name: build
        shell: bash
        run: ./build-scripts/build-win.sh "${{ env.FLUTTER_VERSION }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ./ywallet.zip
            ./YWallet.msix
